Add MI300 details to docs
AMDResearch/omniperf pull request #446
Opened 2024-10-09 17:34 UTC by peterjunpark

## Performance model

- [ ] Update to mention support for MI300
  - [ ] Performance model
  - [ ] MFMA section
- [x] May also want to adopt something like "MI2XX" for MI300A/300X
 
## Pipeline Descriptions

### VALU
- Add MI300 to list of products with MFMA units: https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/pipeline-descriptions.html#vector-arithmetic-logic-unit-valu
- Update note at bottom of section to include MI300 in list of accelerators with 8 waveslots / SIMD
AGPRs
- Add MI300 to MI200 list here: https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/pipeline-descriptions.html#accumulation-vector-general-purpose-registers-agprs
Pipeline Metrics
- Need to add new MFMA instruction metrics for MI300 here:
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/pipeline-metrics.html#mfma-instruction-mix
- And FLOPs for the same here:
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/pipeline-metrics.html#arithmetic-operations
- VALU:
      - Need to find out whether VALU co-issue is publicly mentioned / described in any public document (I suspect it is, but haven't been able to find it)
      - Then need to write a co-issue test, and see how it's reported by Omniperf (I have one we can use), and write it up here:
            - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/pipeline-metrics.html#valu-arithmetic-instruction-mix
            - and add note to scheduler / IPC description here: https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/pipeline-descriptions.html#scheduler
            - This would also make a good addition to the "profiling by example" section

### L1

- Need to update L1 cache-line size here to 128B for MI300+:
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/vector-l1-cache.html#vl1d-cache-access-metrics
UTCL1
- MI300 fixes the bug where hit-on-miss isn't counted: 
      - https://ontrack-internal.amd.com/browse/DEGGIGX90-2974
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/vector-l1-cache.html#l1-unified-translation-cache-utcl1
TA Instruction counts:
- On MI300, we now *theoretically* use the scratch* instructions for stack/spill access, which ... invalidates a lot of this section.  We need to figure out how to rework this:
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/vector-l1-cache.html#instruction-counts
- My original motivation was to *not* expose the HW concept of "TEX" vs "FLAT" to the user, but it may be unavoidable, as AFAIK, scratch* instructions now go through TEX, and we will no longer have any instructions showing up as "generic/spill", even if they're used as such
      - This is slightly alleviated by PC Sampling, when we get it.
Scalar / Instruction cache
- Need to update size and how many CUs it's shared between
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/shader-engine.html
      - 64KB / shared between CUs on MI300

### L2

- L2 is no longer coherence point for MI300+
- L2<->EA request flow diagram needs to be updated for MI300
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/l2-cache.html#request-flow
      - Essentially, we need to add a 128B read request line and figure out how to represent this on the diagram
- Update channel count in text for MI300
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/l2-cache.html#l2-cache-tcc
      - 16 channels *per* XCC, still 256B interleaved
- Update Streaming requests text to also include 300
- Update probe requests text for MI300
      - Likely more involved, need to write some tests to see what triggers these here
- Update note at bottom of section to include MI300:
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/l2-cache.html#l2-cache-accesses
      - 128B cache-line there as well
- L2-Fabric Write and Atomic Bandwidth
      - All atomics are now counted as such on MI300, because they are not cached in L2 and must go to MALL
      - Same with:
            - HBM Write and Atomic Traffic
            - Remote Write and Atomic Traffic
            - Atomic Traffic
            - Uncached Write and Atomic Traffic
- Detailed transaction metrics:
      - https://advanced-micro-devices-demo--362.com.readthedocs.build/projects/omniperf/en/362/conceptual/l2-cache.html#detailed-transaction-metrics
      - Need to add 128B read request metric to table

### Memory Type

- Need to update table (https://rocm.github.io/omniperf/performance_model.html#memory-type) for MI300, may need a better way to represent this as fine-grained/coarse-grained isn't super relevant there anymore.
 
## New concepts
- [ ] Need to discuss XCC / NPS / partitioning modes somewhere.  There's no super logical place to do so, but we might do this in the definitions or as s seperate part of the performance model. 
- [ ] The key points for Omniperf are that:
      - [ ] Number of CUs depends on # of XCCs active in the current partitioning mode
      - [ ] Number of HBM channels per partition (and thus: the achievable L2<->EA bandwidth) depends on the NPS mode
- [ ] Need to discuss MALL as coherence point somewhere
- [ ] Neither of the above need to be in significant detail, IMO
- [ ] Neither of these have **specific** metrics tied to them, but are important to understand how we're presenting data

## References
- [x] Should add MI300 / CDNA3 ISA Guide

2025-01-28 21:42 UTC, skyreflectedinmirrors requested changes
Very good start!

2025-01-28 21:42 UTC, skyreflectedinmirrors commented on docs/conceptual/l2-cache.rst
> +total of up to *eight* instances. Incoming requests are mapped to specific L2
total of up to eight instances (one per XCD)

2025-01-28 21:42 UTC, skyreflectedinmirrors commented on docs/conceptual/l2-cache.rst
> -   :width: 800
last I checked this, it was pretty illegible at smaller widths, but I have to check again

2025-01-28 21:42 UTC, skyreflectedinmirrors commented on docs/conceptual/l2-cache.rst
> +transaction sizes: 32B, 64B, or 128B.
Probably add a sentence like "Not all transaction sizes are supported on all CDNA accelerators / GCN GPUs"

2025-01-28 21:42 UTC, skyreflectedinmirrors commented on docs/conceptual/performance-model.rst
> +   * - Feature
Table seems weird with just one entry right now, but I'm sure we had ideas on how to fill it :P

2025-01-28 21:42 UTC, skyreflectedinmirrors commented on docs/conceptual/performance-model.rst
> +   * - Feature
Oh, right, we probably want to (eventually) take a second pass and go through to find places where we distinguish values based on the architecture, like the waveslots discussion below (or AGPRs), and add them here.

That can probably wait till this is ~ finalized though

2025-01-28 21:42 UTC, skyreflectedinmirrors commented on docs/conceptual/vector-l1-cache.rst
> +   On :ref:`MI200 <mixxx-note>` (CDNA2) accelerators, the UTCL1 does *not*
I'd phrase this like, "On MI200 and *before*..."

2025-01-28 21:42 UTC, skyreflectedinmirrors commented on docs/tutorial/includes/infinity-fabric-transactions.rst
> +   On an AMD MI200 accelerator, for FP32 values this will generate a `global_store_dword` instruction, with the `glc` and `slc` bits set, described in [section 10.1](https://developer.amd.com/wp-cont
we might want a `mixxx-note` here

2025-01-29 20:07 UTC, peterjunpark commented on docs/conceptual/l2-cache.rst
> +total of up to *eight* instances. Incoming requests are mapped to specific L2
Updated to this:
...
The L2 cache consists of several distinct channels. The CDNA3-based :ref:`MI300 <mixxx-note>`
accelerator consists of 16 channels each with a capacity of 256KB and utilizing
256B address interleaving. These channels can operate largely independently and
the system supports up to 8 instances (one per XCD). In constrast, the
:ref:`MI200 <mixxx-note>` and earlier CDNA accelerators have 32 L2 cache
channels each using 256B address interleaving, but only supports a maximum of 2
instances. ...

2025-01-29 20:15 UTC, peterjunpark commented on docs/conceptual/l2-cache.rst
> +transaction sizes: 32B, 64B, or 128B.
Added

2025-01-29 20:39 UTC, skyreflectedinmirrors commented on docs/conceptual/l2-cache.rst
> +total of up to *eight* instances. Incoming requests are mapped to specific L2
I... think for MI200, at best it would be "up to two instances, one per GCD".  And MI100 has 16 channels :P

I forget how we've generally discussed MI200's GCD stuff in these docs, but I think typically we just talk about them like they're entirely separate GPUs.

I would probably do:

> The L2 cache consists of several distinct channels. The CDNA3-based :ref:MI300 <mixxx-note>
accelerator consists of 16 channels each with a capacity of 256KB and utilizing
256B address interleaving. These channels can operate largely independently and
the system supports up to 8 total L2 cache instances (one per XCD). In constrast, the
:ref:MI200 <mixxx-note> CDNA accelerators have 32 L2 cache
channels each using 256B address interleaving, and MI100 CDNA accelerators / GCN GPUs have only 16 L2 Cache channels. ...

cc: @feizheng10 any thoughts?

2025-02-05 19:09 UTC, peterjunpark commented on docs/conceptual/l2-cache.rst
> +total of up to *eight* instances. Incoming requests are mapped to specific L2
Updated [c7bc7bd](https://github.com/ROCm/rocprofiler-compute/pull/446/commits/c7bc7bdf892732342379e9695d43efdc69aea6e7)

2025-02-05 19:09 UTC, peterjunpark commented on docs/conceptual/l2-cache.rst
> -   :width: 800
Right, for some reason, we have to specify a width to let users click on the image to open it.
Added it back. It should be at maximum width.

2025-08-06 18:08 UTC, jayhawk-commits commented
This PR has merge conflicts that need to be resolved. It cannot be automatically imported to the ROCm/rocm-systems super repo.

2025-08-06 18:37 UTC, peterjunpark commented
Closing this @prbasyal-amd

2025-08-06 18:37 UTC, closed without merging