Use Docker to setup development environment
AMDResearch/omniperf pull request #515
Opened 2024-12-17 20:08 UTC by vedithal-amd

2024-12-19 17:35 UTC, feizheng10 requested changes
General speaking, one simple principle we might want to follow is: keep the individual files as less as possible. If the Dockerfile and docker-compose.yml file are only for "dev and quick testing", I'd suggest to move those to a sub_dir in tests(even though we don't have proper structure there yet). Think about we might provide official Dockerfile for the customer to build in the future, I don't want to confuse them later.
And this Dockerfile uses ubuntu-22.04 as base line, we should mention it in the readme.

2024-12-19 20:32 UTC, vedithal-amd commented
Thanks for the comment, Fei.

I was thinking we should move the docker files to a subdir under utils instead of tests since these are technically utility files for the project, what do you think?

2024-12-19 22:11 UTC, feizheng10 approved these changes
LGTM

2024-12-19 22:11 UTC, feizheng10 commented on README.md
> +## Testing
More precisely, this is more about "set up a dev test env", a developer need more info with all the cmake build steps to actually build and test.

2024-12-23 20:29 UTC, vedithal-amd commented on README.md
> +## Testing
Added additional instructions

2025-01-05 02:52 UTC, merged